name: Update the common Platform.sh Repository

on:
  push:
    branches:
      - 'staging'
      - 'main'

jobs:
  update-platform-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Update the Platform Repo Submodule for Frontend
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: novicell-php/DPB-drupal.premium11.headless
          event-type: update-submodule
          client-payload: '{"submodule": "frontend", "branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}'
